name: ci
on: [pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.12', cache: 'poetry' }
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: poetry install --no-interaction --no-ansi
    - name: Run linting
      run: poetry run black --check .
    - name: Run tests
      run: poetry run pytest -v
