name: ci
on: [pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.11', cache: 'poetry' }
    - name: Install deps
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry install --no-interaction
    - name: Lint
      run: poetry run black --check .
    - name: Tests
      run: poetry run pytest -q
